### PR TITLE
replace TravisCI with GitHub Actions CI

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Review by octonato — APPROVED** [review]

**Comment by octonato** [comment]
I'm surprised that this projected is not yet releasing by tag.

**Comment by sullis** [comment]
WDYT? @mkurz

**Comment by sullis** [comment]
@octonato  @mkurz can we merge this?

**Comment by octonato** [comment]
sure, I don't know why it was not merged yet.

**Pull request merged**
